# Generated by Django 5.0 on 2023-12-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membros_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membros',
            name='desenpenho',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='membros',
            name='derrotas',
            field=models.IntegerField(default=0, null=0),
        ),
        migrations.AlterField(
            model_name='membros',
            name='vitorias',
            field=models.IntegerField(default=0, null=0),
        ),
    ]
