# Generated by Django 5.0 on 2023-12-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_membros_desenpenho_alter_membros_derrotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='desenpenho',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
